2020-10-19T16:14:01.2836725-05:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2020-10-19T16:14:01.2862044-05:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2020-10-19T16:14:01.2863585-05:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-10-19T16:14:01.2863780-05:00  [INF] Hosting environment: "Development" (c3307c92)
2020-10-19T16:14:01.2863906-05:00  [INF] Content root path: "E:\source\repos\NichollsScheduler\NichollsScheduler.Api" (b5d60022)
2020-10-19T16:15:09.1992905-05:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2020-10-19T16:15:09.2015555-05:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2020-10-19T16:15:09.2016779-05:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-10-19T16:15:09.2016915-05:00  [INF] Hosting environment: "Development" (c3307c92)
2020-10-19T16:15:09.2017086-05:00  [INF] Content root path: "E:\source\repos\NichollsScheduler\NichollsScheduler.Api" (b5d60022)
2020-10-19T16:15:40.8405627-05:00  [INF] Application is shutting down... (90f52c38)
2020-10-19T16:16:04.1804955-05:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2020-10-19T16:16:04.1829003-05:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2020-10-19T16:16:04.1830281-05:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-10-19T16:16:04.1830423-05:00  [INF] Hosting environment: "Development" (c3307c92)
2020-10-19T16:16:04.1830576-05:00  [INF] Content root path: "E:\source\repos\NichollsScheduler\NichollsScheduler.Api" (b5d60022)
2020-10-19T16:16:34.2459887-05:00 0HM3KEH0QLL1C:00000001 [INF] [10/19/2020 4:16:34 PM] Term list requested. (9909b3e0)
2020-10-19T16:16:34.8325193-05:00 0HM3KEH0QLL1C:00000001 [INF] [10/19/2020 4:16:34 PM] Term list retrived from banner. (1f8e568c)
2020-10-19T16:17:39.3369143-05:00 0HM3KEH0QLL1F:00000001 [INF] [10/19/2020 4:17:39 PM] Searching for CIS 460. (20ed388e)
2020-10-19T16:17:41.4299437-05:00 0HM3KEH0QLL1F:00000001 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.AggregateException: One or more errors occurred. (One or more errors occurred. (No connection could be made because the target machine actively refused it.))
 ---> System.AggregateException: One or more errors occurred. (No connection could be made because the target machine actively refused it.)
 ---> System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it.
 ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at NichollsScheduler.Core.Business.BannerService.GetCourses(CourseModel courseModel, String termId) in E:\source\repos\NichollsScheduler\NichollsScheduler.Core\Business\BannerService.cs:line 143
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at NichollsScheduler.Core.Business.BannerService.<>c__DisplayClass8_0.<GetCourseResults>b__0(CourseModel courseModel) in E:\source\repos\NichollsScheduler\NichollsScheduler.Core\Business\BannerService.cs:line 119
   at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList`1 list, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at NichollsScheduler.Core.Business.BannerService.GetCourseResults(List`1 courses, String termId) in E:\source\repos\NichollsScheduler\NichollsScheduler.Core\Business\BannerService.cs:line 116
   at NichollsScheduler.Api.Controllers.ApiController.SearchCourses(List`1 courses, String termId) in E:\source\repos\NichollsScheduler\NichollsScheduler.Api\Controllers\ApiController.cs:line 47
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-10-19T16:19:07.0632803-05:00 0HM3KEH0QLL1H:00000001 [INF] [10/19/2020 4:19:06 PM] Searching for CIS 460. (31687cf5)
2020-10-19T16:19:47.8318148-05:00 0HM3KEH0QLL1H:00000001 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.AggregateException: One or more errors occurred. (One or more errors occurred. (No connection could be made because the target machine actively refused it.))
 ---> System.AggregateException: One or more errors occurred. (No connection could be made because the target machine actively refused it.)
 ---> System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it.
 ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at NichollsScheduler.Core.Business.BannerService.GetCourses(CourseModel courseModel, String termId) in E:\source\repos\NichollsScheduler\NichollsScheduler.Core\Business\BannerService.cs:line 143
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at NichollsScheduler.Core.Business.BannerService.<>c__DisplayClass8_0.<GetCourseResults>b__0(CourseModel courseModel) in E:\source\repos\NichollsScheduler\NichollsScheduler.Core\Business\BannerService.cs:line 119
   at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList`1 list, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at NichollsScheduler.Core.Business.BannerService.GetCourseResults(List`1 courses, String termId) in E:\source\repos\NichollsScheduler\NichollsScheduler.Core\Business\BannerService.cs:line 116
   at NichollsScheduler.Api.Controllers.ApiController.SearchCourses(List`1 courses, String termId) in E:\source\repos\NichollsScheduler\NichollsScheduler.Api\Controllers\ApiController.cs:line 47
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-10-19T16:25:29.5708498-05:00  [INF] Application is shutting down... (90f52c38)
2020-10-19T16:25:33.1893749-05:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2020-10-19T16:25:33.1916463-05:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2020-10-19T16:25:33.1917692-05:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-10-19T16:25:33.1917825-05:00  [INF] Hosting environment: "Development" (c3307c92)
2020-10-19T16:25:33.1917947-05:00  [INF] Content root path: "E:\source\repos\NichollsScheduler\NichollsScheduler.Api" (b5d60022)
2020-10-19T16:25:48.4237685-05:00 0HM3KEM5KQ2AA:00000001 [INF] [10/19/2020 4:25:48 PM] Term list requested. (0734b5ff)
2020-10-19T16:25:48.9201589-05:00 0HM3KEM5KQ2AA:00000001 [INF] [10/19/2020 4:25:48 PM] Term list retrived from banner. (d9578ccc)
2020-10-19T16:26:05.9728035-05:00 0HM3KEM5KQ2AD:00000001 [INF] [10/19/2020 4:26:05 PM] Searching for CIS 460. (012196f5)
2020-10-19T16:26:08.0200100-05:00 0HM3KEM5KQ2AD:00000001 [FTL] [10/19/2020 4:26:08 PM] Unable to connect to banner. (572e71bf)
2020-10-19T16:26:08.0485482-05:00 0HM3KEM5KQ2AD:00000001 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.AggregateException: One or more errors occurred. (One or more errors occurred. (Object reference not set to an instance of an object.))
 ---> System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at NichollsScheduler.Core.Business.BannerService.GetCourses(CourseModel courseModel, String termId) in E:\source\repos\NichollsScheduler\NichollsScheduler.Core\Business\BannerService.cs:line 150
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at NichollsScheduler.Core.Business.BannerService.<>c__DisplayClass8_0.<GetCourseResults>b__0(CourseModel courseModel) in E:\source\repos\NichollsScheduler\NichollsScheduler.Core\Business\BannerService.cs:line 119
   at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList`1 list, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at NichollsScheduler.Core.Business.BannerService.GetCourseResults(List`1 courses, String termId) in E:\source\repos\NichollsScheduler\NichollsScheduler.Core\Business\BannerService.cs:line 116
   at NichollsScheduler.Api.Controllers.ApiController.SearchCourses(List`1 courses, String termId) in E:\source\repos\NichollsScheduler\NichollsScheduler.Api\Controllers\ApiController.cs:line 47
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-10-19T16:26:43.7446502-05:00 0HM3KEM5KQ2AF:00000001 [INF] [10/19/2020 4:26:43 PM] Term list requested. (3029c458)
2020-10-19T16:26:43.7448688-05:00 0HM3KEM5KQ2AF:00000001 [INF] [10/19/2020 4:26:43 PM] Term list retrived from cache. (4925f4f1)
2020-10-19T16:26:52.8717319-05:00 0HM3KEM5KQ2AJ:00000001 [INF] [10/19/2020 4:26:52 PM] Searching for CIS 460. (6fc65c5e)
2020-10-19T16:26:53.3637694-05:00 0HM3KEM5KQ2AJ:00000001 [INF] [10/19/2020 4:26:53 PM] Went to banner and found CIS 460. (fbc19db9)
2020-10-19T16:26:53.3643148-05:00 0HM3KEM5KQ2AJ:00000001 [INF] [10/19/2020 4:26:53 PM] Match not found for CIS 460 from banner. (6a784d6a)
2020-10-19T16:27:14.3325900-05:00 0HM3KEM5KQ2AL:00000001 [INF] [10/19/2020 4:27:14 PM] Searching for CIS 460. (b8865d00)
2020-10-19T16:27:14.7597032-05:00 0HM3KEM5KQ2AL:00000001 [INF] [10/19/2020 4:27:14 PM] Went to banner and found CIS 460. (72bc6969)
2020-10-19T16:27:14.7599042-05:00 0HM3KEM5KQ2AL:00000001 [INF] [10/19/2020 4:27:14 PM] Match not found for CIS 460 from banner. (6899f039)
2020-10-19T16:27:33.6362648-05:00 0HM3KEM5KQ2AN:00000001 [INF] [10/19/2020 4:27:33 PM] Term list requested. (8c3853ae)
2020-10-19T16:27:33.6370239-05:00 0HM3KEM5KQ2AN:00000001 [INF] [10/19/2020 4:27:33 PM] Term list retrived from cache. (aebfe14a)
2020-10-19T16:27:42.5998967-05:00 0HM3KEM5KQ2AQ:00000001 [INF] [10/19/2020 4:27:42 PM] Searching for CIS 460. (d279f955)
2020-10-19T16:27:42.6000764-05:00 0HM3KEM5KQ2AQ:00000001 [INF] [10/19/2020 4:27:42 PM] Match found in cache for CIS 460. (2b542f5d)
2020-10-19T16:27:42.6002721-05:00 0HM3KEM5KQ2AQ:00000001 [FTL] [10/19/2020 4:27:42 PM] Unable to connect to banner. (697acc35)
2020-10-19T16:27:56.7917237-05:00 0HM3KEM5KQ2AS:00000001 [INF] [10/19/2020 4:27:56 PM] Searching for CIS 460. (9eb5ee70)
2020-10-19T16:27:56.7919255-05:00 0HM3KEM5KQ2AS:00000001 [INF] [10/19/2020 4:27:56 PM] Match found in cache for CIS 460. (b344f480)
2020-10-19T16:27:56.7921541-05:00 0HM3KEM5KQ2AS:00000001 [FTL] [10/19/2020 4:27:56 PM] Unable to connect to banner. (3b24046a)
2020-10-19T16:28:06.6307839-05:00  [INF] Application is shutting down... (90f52c38)
2020-10-19T16:28:10.8775956-05:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2020-10-19T16:28:10.8799481-05:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2020-10-19T16:28:10.8800759-05:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-10-19T16:28:10.8800922-05:00  [INF] Hosting environment: "Development" (c3307c92)
2020-10-19T16:28:10.8801089-05:00  [INF] Content root path: "E:\source\repos\NichollsScheduler\NichollsScheduler.Api" (b5d60022)
2020-10-19T16:28:14.4736791-05:00 0HM3KENH0UQGQ:00000001 [INF] [10/19/2020 4:28:14 PM] Searching for CIS 460. (c3f947bc)
2020-10-19T16:28:15.0880621-05:00 0HM3KENH0UQGQ:00000001 [INF] [10/19/2020 4:28:15 PM] Went to banner and found CIS 460. (f4555b77)
2020-10-19T16:28:15.0885822-05:00 0HM3KENH0UQGQ:00000001 [INF] [10/19/2020 4:28:15 PM] Match not found for CIS 460 from banner. (e31571bc)
2020-10-19T16:29:28.4052111-05:00 0HM3KENH0UQGR:00000001 [INF] [10/19/2020 4:29:28 PM] Searching for CIS 460. (9c4e2165)
2020-10-19T16:29:28.4054407-05:00 0HM3KENH0UQGR:00000001 [INF] [10/19/2020 4:29:28 PM] Match found in cache for CIS 460. (38a39be7)
2020-10-19T16:29:28.4056005-05:00 0HM3KENH0UQGR:00000001 [FTL] [10/19/2020 4:29:28 PM] Unable to connect to banner. (e6a3d367)
2020-10-19T16:29:32.1519261-05:00  [INF] Application is shutting down... (90f52c38)
2020-10-19T16:29:35.8405350-05:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2020-10-19T16:29:35.8431383-05:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2020-10-19T16:29:35.8432893-05:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-10-19T16:29:35.8433100-05:00  [INF] Hosting environment: "Development" (c3307c92)
2020-10-19T16:29:35.8433234-05:00  [INF] Content root path: "E:\source\repos\NichollsScheduler\NichollsScheduler.Api" (b5d60022)
2020-10-19T16:29:45.4188268-05:00 0HM3KEOAGHM8H:00000001 [INF] [10/19/2020 4:29:45 PM] Searching for CIS 460. (fcdd9407)
2020-10-19T16:29:46.0371265-05:00 0HM3KEOAGHM8H:00000001 [INF] [10/19/2020 4:29:46 PM] Went to banner and found CIS 460. (80582658)
2020-10-19T16:29:56.8022835-05:00 0HM3KEOAGHM8J:00000001 [INF] [10/19/2020 4:29:56 PM] Term list requested. (0b514c43)
2020-10-19T16:29:58.8956162-05:00 0HM3KEOAGHM8J:00000001 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.Exception: Error. There was an issue getting the available terms.
   at NichollsScheduler.Core.Business.BannerService.GetTerms() in E:\source\repos\NichollsScheduler\NichollsScheduler.Core\Business\BannerService.cs:line 108
   at NichollsScheduler.Api.Controllers.ApiController.GetAvailableTerms() in E:\source\repos\NichollsScheduler\NichollsScheduler.Api\Controllers\ApiController.cs:line 25
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-10-19T16:30:15.6999140-05:00 0HM3KEOAGHM8L:00000001 [INF] [10/19/2020 4:30:15 PM] Term list requested. (97f35a02)
2020-10-19T16:30:16.0649063-05:00 0HM3KEOAGHM8L:00000001 [INF] [10/19/2020 4:30:16 PM] Term list retrived from banner. (a1c419ad)
2020-10-19T16:30:27.6658545-05:00 0HM3KEOAGHM8O:00000001 [INF] [10/19/2020 4:30:27 PM] Searching for CIS 460. (bd44128f)
2020-10-19T16:30:29.7120592-05:00 0HM3KEOAGHM8O:00000001 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.AggregateException: One or more errors occurred. (One or more errors occurred. (No connection could be made because the target machine actively refused it.))
 ---> System.AggregateException: One or more errors occurred. (No connection could be made because the target machine actively refused it.)
 ---> System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it.
 ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at NichollsScheduler.Core.Business.BannerService.GetCourses(CourseModel courseModel, String termId) in E:\source\repos\NichollsScheduler\NichollsScheduler.Core\Business\BannerService.cs:line 143
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at NichollsScheduler.Core.Business.BannerService.<>c__DisplayClass8_0.<GetCourseResults>b__0(CourseModel courseModel) in E:\source\repos\NichollsScheduler\NichollsScheduler.Core\Business\BannerService.cs:line 119
   at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList`1 list, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at NichollsScheduler.Core.Business.BannerService.GetCourseResults(List`1 courses, String termId) in E:\source\repos\NichollsScheduler\NichollsScheduler.Core\Business\BannerService.cs:line 116
   at NichollsScheduler.Api.Controllers.ApiController.SearchCourses(List`1 courses, String termId) in E:\source\repos\NichollsScheduler\NichollsScheduler.Api\Controllers\ApiController.cs:line 47
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-10-19T16:30:56.2622887-05:00  [INF] Application is shutting down... (90f52c38)
